name: UltimateLevels
author: BlackCult
version: 1.0.1
main: it.blackcult.ultimatelevels.UltimateLevels
softdepend: [Vault, PlaceholderAPI]
api-version: '1.19'
commands:
  levels:
    description: Open the main inventory
  ultimatelevels:
    description: Admin commands

